update

diff --git a/test_case b/test_case
--- a/test_case
+++ b/test_case
@@ -28,10 +28,27 @@ export 123=KEY
 # if the content of the file is test1\n test2\n, ours write 2 into outfile, while bash write 1
 
 
-# exit 100 is not exiting
-# exit +100 show as syntax error
+exit 100 is not exiting
+exit +100 show as syntax error
 
 #HEREDOC: signal part
 
 
 #EXITSTATUS
+
+
+
+
+ls  <"./test_files/infile_big" | echo <  env.c > out
+
+# Malloc failed: Cannot allocate memory
+
+echo <"./test_files/infile_big" | echo <"./test_files/infile"
+# error msg is not correct
+
+
+cat <"./test_files/infile" | echo hi
+# hi is not printed on the terminal. Why????
+
+echo infile | echo hi
+# output is hi, but no error msg about the missing infile
